services:
  mongo:
    image: mongo:latest
    container_name: wyd_saas_mongo_db
    ports:
      - "28017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: always
    networks:
      - wyd_saas_network

  mongo_web:
    image: mongo-express
    container_name: wyd_saas_mongo_web
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: toor

      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    restart: always
    networks:
      - wyd_saas_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wyd_saas_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor
    restart: always
    networks:
      - wyd_saas_network

networks:
  wyd_saas_network:
    driver: bridge
